### ISSUE TITLE
Push down button getting stuck inconsistently 

### ISSUE THREAD

**Issue by jversloot** [makersmakingchange/Spruce-Mini-Joystick#2]
On some builds, using the generic joystick module with headers, when the push button is tested on its own it works as expected, but when tested on the Forest Hub or XAC, when both the joystick and the switch are plugged in, at times the button appears to be pressed down after being released, as if it were "stuck on". If just the button is plugged in and not the joystick this doesn't happen, or if the joystick is plugged into the device (Forest or XAC) and the button is plugged into a switch tester this doesn't happen either.

**Comment by stephandobri** [comment]
Bug fixed. Cause was connecting the tip of the mono cable to the ground pin on the generic PS2 joystick module.
The Maker Guide was updated to have makers double check the wires corresponding to the tip and sleeve of the mono cable, and telling them which needs to be connected to ground.
